image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      npm install
    command: |
      echo "Starting Ambianic UI in dev mode:"
      npm run serve
  - command: |
      echo "Waiting for npm install to finish"
      gp await-port 8080 && gp preview $(gp url 8080)/index.html
      echo "Starting Ambianic PWA testsuite"
      npm install cypress
      npm run test

vscode:
  extensions:
    - octref.vetur@0.31.3:QHyAEoimIBiRDoL6WtEoRg==

ports:
  - port: 8080

github:
  prebuilds:
    addComment: true

